### ISSUE TITLE
Perf optimisation: prefer strings over streams?

### ISSUE THREAD

**Issue by popeindustries** [almost/stream-template#6]
I've had a chance to run some stress tests with a "production" template tree to measure the overhead associated with treating all templates as `Streams` as default instead of `Strings`. Rendering a template tree with 6-8 levels of nested templates (mostly `Strings`, some `Promises` and `Arrays`) resulted in the following when all templates were processed with `stream-template`:

```bash
> autocannon -c 100 -d 5 -p 10 http://localhost:3000/1.13377671

Running 5s test @ http://localhost:3000/1.13377671
100 connections with 10 pipelining factor

Stat         Avg     Stdev  Max     
Latency (ms) 167.44  614.22 4070.71 
Req/Sec      472     13.27  490     
Bytes/Sec    8.36 MB 254 kB 8.58 MB 

2k requests in 5s, 41.3 MB read
```

Defaulting to `Strings` and deopting when hitting an `object` interpolation with the following code:

```js
function fastTemplate(strings, ...interpolations) {
  let str = strings[0];

  for (let i = 0, n = interpolations.length; i < n; i++) {
    const interpolation = interpolations[i];
    // Deopt if not primitive type
    if (typeof interpolation === 'object') {
      return streamTemplate([str, ...strings.slice(i + 1)], ...interpolations.slice(i));
    }

    str += interpolations[i];
    str += strings[i + 1];
  }

  return str;
}
```

...resulted in a ~4x throughput increase:

```bash
> autocannon -c 100 -d 5 -p 10 http://localhost:3000/1.13377671

Running 5s test @ http://localhost:3000/1.13377671
100 connections with 10 pipelining factor

Stat         Avg     Stdev   Max     
Latency (ms) 56.55   180.16  1346.15 
Req/Sec      1678    369.8   1970    
Bytes/Sec    29.4 MB 6.56 MB 34.5 MB 

8k requests in 5s, 147 MB read
```

The only potential weakness I can see with this approach is that, depending on the tree, you would end up with either a `String` or a `Stream` as output. This is not a problem for us since we are using a server framework that accepts either type in it's `res.send()` method, but it's not ideal. I think it would be best to be able to mark the entry template as "root" to enforce a `Stream` return type, but I'm not entirely sure how this could work. In any case, it's an interesting opportunity!

**Comment by popeindustries** [comment]
Of course, a good question would be: "why not just use regular template literals when writing string content?" Because when generating HTML it's nice to get syntax highlighting when using a tag named `html` 😜 

And you don't have to know what nested components are returning:

```js
  return html`<html>
    ${Head(data)}
    <body>
      ${Body(data)}
      ${Footer(data)}
    </body>
  </html>`
```

**Comment by almost** [comment]
I wouldn't be opposed to adding a performance optimization. But I would want to keep the semantics consistent. So sometimes returning a string and sometimes a stream would be a big no for me. But as long as you can make it just a internal performance enhancement then I'd be for it!

**Comment by popeindustries** [comment]
I agree about not changing the semantics, but I’m a little stuck on what heuristics to use. More thought needed!
